#!/bin/bash
./build.py
rm -rf ~/Library/Application\ Support/Titanium/modules/iphone/it.smc.dakeyboardcontrol
unzip \
	it.smc.dakeyboardcontrol-iphone-0.2.1.zip \
	-d ~/Library/Application\ Support/Titanium/
